name: first_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

fonts:
  - family: MysticFont
    fonts:
      - asset: fonts/MysticFont-Regular.ttf


dependencies:
  font_awesome_flutter: ^10.1.0
  awesome_notifications: ^0.9.3+1
  flutter:
    sdk: flutter
  flame: ^1.19.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png # background pic
    - assets/images/Necromancer.png  # Necromancer sprite sheet
    - assets/images/Fire_WarriorFireSword-Sheet.png  # Fire Warrior sprite sheet
    - assets/images/wind_SpriteSheet_288x128.png  # Wind Warrior sprite sheet
    - assets/images/female_knight_idle.png # female knight idle sprite sheet
    - assets/images/blue_witch_idle.png # blue witch idle sprite sheet
    - assets/images/Sliderbackground.png # Slider background image for taskSliderScreen 
    - assets/images/Cave.png # Cave background image for difficulty screen  
    - assets/images/boss_demon_slime_FREE_v1.0/individual sprites/01_demon_idle/demon_idle_1.png # Boss image 
    - assets/images/boss_demon_slime_FREE_v1.0/spritesheets/demon_slime_FREE_v1.0_288x160_spritesheet.png