// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4RwDt73SG63fMIIZODY0dDRF1HpKUZbM',
    appId: '1:874180898186:android:8f74d90f9512aa51b86c73',
    messagingSenderId: '874180898186',
    projectId: 'agile-pro-d2309',
    storageBucket: 'agile-pro-d2309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDquAcUDxNh1upo5kSEsRbigGjVmS5bW8I',
    appId: '1:874180898186:ios:b5338588767cd261b86c73',
    messagingSenderId: '874180898186',
    projectId: 'agile-pro-d2309',
    storageBucket: 'agile-pro-d2309.appspot.com',
    iosClientId: '874180898186-huatgiahhc2qjfhmhksn4n8so03pkgdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVqYVumztmHcUDyWsj3RWDWX3-vYxRinM',
    appId: '1:874180898186:web:f9e8944b7b256ccdb86c73',
    messagingSenderId: '874180898186',
    projectId: 'agile-pro-d2309',
    authDomain: 'agile-pro-d2309.firebaseapp.com',
    storageBucket: 'agile-pro-d2309.appspot.com',
    measurementId: 'G-Q9JB6SL2NH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDquAcUDxNh1upo5kSEsRbigGjVmS5bW8I',
    appId: '1:874180898186:ios:b5338588767cd261b86c73',
    messagingSenderId: '874180898186',
    projectId: 'agile-pro-d2309',
    storageBucket: 'agile-pro-d2309.appspot.com',
    iosClientId: '874180898186-huatgiahhc2qjfhmhksn4n8so03pkgdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVqYVumztmHcUDyWsj3RWDWX3-vYxRinM',
    appId: '1:874180898186:web:5a5e6d684dc59691b86c73',
    messagingSenderId: '874180898186',
    projectId: 'agile-pro-d2309',
    authDomain: 'agile-pro-d2309.firebaseapp.com',
    storageBucket: 'agile-pro-d2309.appspot.com',
    measurementId: 'G-VLQ7DQPERH',
  );

}